
---
apiVersion: v1
data:
    vcap-properties.yaml: dmNhcC5hcHBsaWNhdGlvbi5saW1pdHMuZGlzazogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLmxpbWl0cy5mZHM6IDE2Mzg0CnZjYXAuYXBwbGljYXRpb24ubGltaXRzLm1lbTogMTAyNAp2Y2FwLmFwcGxpY2F0aW9uLm5hbWU6IGN1c3RvbWVycwp2Y2FwLmFwcGxpY2F0aW9uLnNwYWNlX2lkOiAzMDJmZmUwYy0zODNkLTQ0Y2EtODcyYi1hZjc3YmM1OWY2M2YKdmNhcC5hcHBsaWNhdGlvbi5zcGFjZV9uYW1lOiBlbnRlcnByaXNlCnZjYXAuYXBwbGljYXRpb24udXJpczogZW50ZXJwcmlzZS1hcHAtNTI1MjEwODM5LWN1c3RvbWVycy4yMC4yMzEuMTIxLjE4NC5uaXAuaW8KdmNhcC5hcHBsaWNhdGlvbi51cmlzWzBdOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4MzktY3VzdG9tZXJzLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX2lkOiA0OWE2MGNkYi1iZTBmLTQwNzItOWFlMC1jNGNhMTMxOTZiMDYKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl92ZXJzaW9uOiAwNzYzMTMwNC0xNzViLTQxYjgtODUwOC1kMmM4NmMwYWQ5NGQKdmNhcC5hcHBsaWNhdGlvbi5jZl9hcGk6IGh0dHBzOi8vYXBpLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLnVzZXJzOiAKdmNhcC5hcHBsaWNhdGlvbi52ZXJzaW9uOiAwNzYzMTMwNC0xNzViLTQxYjgtODUwOC1kMmM4NmMwYWQ5NGQKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl9uYW1lOiBjdXN0b21lcnMKdmNhcC5hcHBsaWNhdGlvbi5hcHBsaWNhdGlvbl91cmlzOiBlbnRlcnByaXNlLWFwcC01MjUyMTA4MzktY3VzdG9tZXJzLjIwLjIzMS4xMjEuMTg0Lm5pcC5pbwp2Y2FwLmFwcGxpY2F0aW9uLmFwcGxpY2F0aW9uX3VyaXNbMF06IGVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1jdXN0b21lcnMuMjAuMjMxLjEyMS4xODQubmlwLmlv
kind: Secret
metadata:
    creationTimestamp: null
    name: customers-vcapasspringbootproperties
type: Opaque

...
