
---
apiVersion: v1
data:
    VCAP_APPLICATION: eyJhcHBsaWNhdGlvbl9pZCI6Ijg3MzUzOTNiLWExZjctNDIxMS1hNmIzLTQ1OWE3YzVlNjc0OSIsImFwcGxpY2F0aW9uX25hbWUiOiJpbnZlbnRvcnkiLCJhcHBsaWNhdGlvbl91cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1pbnZlbnRvcnkuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sImFwcGxpY2F0aW9uX3ZlcnNpb24iOiIxMTZmN2E4Ni03NTQzLTRkOWItYTJlNS1jYWQ3OWViYTA2YTAiLCJjZl9hcGkiOiJodHRwczovL2FwaS4yMC4yMzEuMTIxLjE4NC5uaXAuaW8iLCJsaW1pdHMiOnsiZGlzayI6MTAyNCwiZmRzIjoxNjM4NCwibWVtIjoxMDI0fSwibmFtZSI6ImludmVudG9yeSIsInNwYWNlX2lkIjoiMzAyZmZlMGMtMzgzZC00NGNhLTg3MmItYWY3N2JjNTlmNjNmIiwic3BhY2VfbmFtZSI6ImVudGVycHJpc2UiLCJ1cmlzIjpbImVudGVycHJpc2UtYXBwLTUyNTIxMDgzOS1pbnZlbnRvcnkuMjAuMjMxLjEyMS4xODQubmlwLmlvIl0sInVzZXJzIjpudWxsLCJ2ZXJzaW9uIjoiMTE2ZjdhODYtNzU0My00ZDliLWEyZTUtY2FkNzllYmEwNmEwIn0=
    VCAP_SERVICES: e30=
kind: Secret
metadata:
    creationTimestamp: null
    name: inventory-vcapasenv
type: Opaque

...
