
---
apiVersion: v1
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjogewoJCQkiYXV0aCI6ICJhbTlpYVc1c05EQXdaWGs2U213ME15UnphR0ZyZEdreE9UazAiCgkJfQoJfQp9
kind: Secret
metadata:
    creationTimestamp: null
    name: quay-io-imagepullsecret
type: kubernetes.io/dockerconfigjson

...
