
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: gateway
    name: gateway
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - env:
                    - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
                      value: '{ enabled: false }'
                    - name: SPRING_PROFILES_ACTIVE
                      value: dev
                    - name: VCAP_SERVICES
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_SERVICES
                            name: gateway-vcapasenv
                    - name: VCAP_APPLICATION
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_APPLICATION
                            name: gateway-vcapasenv
                    - name: ENTERPRISE_APP_INVENTORY_URL
                      value: http://enterprise-app-525210839-inventory.20.231.121.184.nip.io/products
                    - name: ENTERPRISE_APP_ORDERS_URL
                      value: http://enterprise-app-525210839-orders.20.231.121.184.nip.io/orders
                    - name: ENTERPRISE_APP_CUSTOMERS_URL
                      value: http://enterprise-app-525210839-customers.20.231.121.184.nip.io/customers
                    - name: SPRING_CONFIG_IMPORT
                      value: /vcap/vcap-properties.yaml
                  image: quay.io/jobinl400ey/gateway:latest
                  imagePullPolicy: Always
                  name: gateway
                  ports:
                    - containerPort: 8080
                  resources:
                    requests:
                        ephemeral-storage: 1024M
                        memory: 1024M
                  volumeMounts:
                    - mountPath: /vcap
                      name: vcapsecretvolume
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
            volumes:
                - name: vcapsecretvolume
                  secret:
                    secretName: gateway-vcapasspringbootproperties
status: {}

...
