
---
apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: gateway
    name: gateway
spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            move2kube.konveyor.io/service: gateway
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                move2kube.konveyor.io/service: gateway
            name: gateway
        spec:
            containers:
                - env:
                    - name: JBP_CONFIG_SPRING_AUTO_RECONFIGURATION
                      value: '{ enabled: false }'
                    - name: SPRING_PROFILES_ACTIVE
                      value: dev
                    - name: VCAP_SERVICES
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_SERVICES
                            name: gateway-vcapasenv
                    - name: VCAP_APPLICATION
                      valueFrom:
                        secretKeyRef:
                            key: VCAP_APPLICATION
                            name: gateway-vcapasenv
                    - name: ENTERPRISE_APP_INVENTORY_URL
                      value: http://enterprise-app-525210839-inventory.20.231.121.184.nip.io/products
                    - name: ENTERPRISE_APP_ORDERS_URL
                      value: http://enterprise-app-525210839-orders.20.231.121.184.nip.io/orders
                    - name: ENTERPRISE_APP_CUSTOMERS_URL
                      value: http://enterprise-app-525210839-customers.20.231.121.184.nip.io/customers
                    - name: SPRING_CONFIG_IMPORT
                      value: /vcap/vcap-properties.yaml
                  image: quay.io/jobinl400ey/gateway:latest
                  imagePullPolicy: Always
                  name: gateway
                  ports:
                    - containerPort: 8080
                      protocol: TCP
                  resources:
                    requests:
                        ephemeral-storage: 1024M
                        memory: 1024M
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                  volumeMounts:
                    - mountPath: /vcap
                      name: vcapsecretvolume
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
            volumes:
                - name: vcapsecretvolume
                  secret:
                    defaultMode: 420
                    secretName: gateway-vcapasspringbootproperties
status: {}

...
